// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee-service.proto

package com.aexp.observability.monitoring.apppromethiusprototype.employee;

public interface EmployeeRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:EmployeeRequest)
    com.google.protobuf.MessageOrBuilder {

  /** <code>string emp_id = 1;</code> */
  String getEmpId();
  /** <code>string emp_id = 1;</code> */
  com.google.protobuf.ByteString getEmpIdBytes();
}
